export const defaultSchema = {
	strip: ['script'],
	clobberPrefix: 'user-content-',
	clobber: ['name', 'id'],
	ancestors: {
		tbody: ['table'],
		tfoot: ['table'],
		thead: ['table'],
		td: ['table'],
		th: ['table'],
		tr: ['table'],
	},
	protocols: {
		href: ['http', 'https', 'mailto', 'xmpp', 'irc', 'ircs'],
		cite: ['http', 'https'],
		src: ['http', 'https'],
		longDesc: ['http', 'https'],
	},
	tagNames: [
		'h1','h2','h3','h4','h5','h6','br','b','i','strong','em','a',
		'pre','code','img','tt','div','ins','del','sup','sub','p','ol',
		'ul','table','thead','tbody','tfoot','blockquote','dl','dt','dd',
		'kbd','q','samp','var','hr','ruby','rt','rp','li','tr','td','th',
		's','strike','summary','details','caption','figure','figcaption',
		'abbr','bdo','cite','dfn','mark','small','span','time','wbr',
		'input',
	],
	attributes: {
		a: {href:true},
		img: {src:true, longDesc:true},
		input: {
			type: 'checkbox',
			disabled: "",
		},
		li: {
			className: 'task-list-item',
		},
		div: {itemScope:true, itemType:true},
		blockquote: {cite:true},
		del: {cite:true},
		ins: {cite:true},
		q: {cite:true},
	},
	globalAttributes: {
		abbr:true, accept:true, acceptCharset:true, accessKey:true,
		action:true, align:true, alt:true, ariaDescribedBy:true,
		ariaHidden:true, ariaLabel:true, ariaLabelledBy:true, axis:true,
		border:true, cellPadding:true, cellSpacing:true, char:true,
		charOff:true, charSet:true, checked:true, clear:true, cols:true,
		colSpan:true, color:true, compact:true, coords:true,
		dateTime:true, dir:true, disabled:true, encType:true,
		htmlFor:true, frame:true, headers:true, height:true,
		hrefLang:true, hSpace:true, isMap:true, id:true, label:true,
		lang:true, maxLength:true, media:true, method:true, multiple:true,
		name:true, noHref:true, noShade:true, noWrap:true, open:true,
		prompt:true, readOnly:true, rel:true, rev:true, rows:true,
		rowSpan:true, rules:true, scope:true, selected:true, shape:true,
		size:true, span:true, start:true, summary:true, tabIndex:true,
		target:true, title:true, type:true, useMap:true, vAlign:true,
		value:true, vSpace:true, width:true, itemProp:true,
	},
	required: {
		input: {
			type: 'checkbox',
			disabled: "",
		},
	},
}
