// this is only used for links generated by markdown, not raw html like <a> or <img>
// so, i've disabled it, since we need to sanitize ALL urls later anyway

// this normally filters urls based on their protocol

// we also use a hack that inserts another property in order to detect which images and links are generated by markdown and which are from html
export function sanitizeUri(url, protocols) {
	url = url.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;")
	return url+'" data--markdownlink="'
}
// normally this would just be encodeURI() except that % sequences are left unchanged.
// i.e. encodeURI(url).replace(/%25([a-zA-Z0-9]{2})/g, "%$1") 
export function normalizeUri(url) {
	return url
}
